
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/DePhoegon/biome_debase_bridge/issues/" #optional
[[mods]] #mandatory
modId="delbridgebop" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Delbase Bridge - BOP" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="dephoegonlogo.png" #optional
credits="Thanks to Certain people for some tutorials"
authors="DePhoegon"
description='''
This is a Bridge mod for two mods [delbase] DePhoegons' Reclaim & [biomesoplenty] Biomes O' Plenty.

Creating the Missing blocks that would exist if Biomes O' Plenty blocks existed within the base game & give DePhoegons' Reclaims the blocks it would have had.
'''
[[dependencies.delbridgebop]] 
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delbridgebop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delbridgebop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delbridgebop]]
    modId="delbase"
    mandatory=true
    versionRange="[1.2,1.3,1.4,1.5)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delbridgebop]]
    modId="terrablender"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"